[MQTT]
MQTT_BROKER = 127.0.0.1
MQTT_PORT = 1883
MQTT_TOPIC = org/unibo/cluster/theta
MQTT_USER=
MQTT_PASSWORD=

[Daemon]
TS = 10
LOG_LEVEL = INFO
LOG_FILENAME = nvml_pub.log
PID_FILENAME = nvml_pub.pid
METRICS = gpu_util, mem_used, temp, power, graphics_clock, memory_clock
